[package]
name = "anagram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
arrayvec = "0.7.2"
smallvec = { version = "1.7.0", features = ["union"] }